version: '3.6'

networks:
  frontend:
    name: frontend

services:
  webapp:
    image: webapp:latest
    build:
      context: ../../..
      dockerfile: fbcnms-projects/magmanms/docker/Dockerfile
    networks:
      - frontend
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
      - ENVIRONMENT=${ENVIRONMENT}
      - PARTNER=${PARTNER}
    env_file:
      - envs/build-nms.env
  db:
    image: mysql:5
    env_file:
      - envs/build-db.env
    restart: always
    networks:
      - frontend
    expose:
      - '3306'
