---
swagger: '2.0'
info:
  title: Dnsd Model Definitions and Paths
  description: Magma REST APIs
  version: 1.0.0

paths:
  /networks/{network_id}/configs/dns:
    post:
      summary: Create Network DNS Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: config
        description: New config
        required: true
        schema:
          $ref: '#/definitions/network_dns_config'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    get:
      summary: Retrieve Network DNS Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: Current network DNS configuration
          schema:
            $ref: '#/definitions/network_dns_config'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify Network DNS Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: config
        description: Updated config
        required: true
        schema:
          $ref: '#/definitions/network_dns_config'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete Network DNS Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

definitions:
  network_dns_config:
    description: DNS configuration for a network
    type: object
    properties:
      enable_caching:
        type: boolean
        example: false
      local_ttl:
        type: integer
        format: int32
        example: 0
      records:
        type: array
        items:
          # DNS mapping
          description: Mapping used for DNS resolving from a domain
          type: object
          properties:
            domain:
              type: string
              minLength: 1
              x-nullable: false
              example: example.com
            a_record:
              type: array
              items:
                type: string
                minLength: 1
                x-nullable: false
                example: 192.88.99.142
            aaaa_record:
              type: array
              items:
                type: string
                minLength: 1
                x-nullable: false
                example: 2001:0db8:85a3:0000:0000:8a2e:0370:7334 # TODO: Regex?
            cname_record:
              type: array
              items:
                type: string
                minLength: 1
                x-nullable: false
                example: cname.example.com