---
# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Delete /var/cache/apt/archives if exists
  file: path=/var/cache/apt/archives state=absent
  when: full_provision

- name: Create a local directory for apt cache if not exist
  file: path={{ apt_cache_directory }} state=directory
  when: full_provision

- name: Create symlink for apt cache
  file: src='{{ apt_cache_directory }}' path=/var/cache/apt/archives state=link force=yes
  when: full_provision
