---
# file: tasks/main.yml
# Top-level installer for Prometheus.
#
# @see https://github.com/prometheus/prometheus
# @see http://prometheus.io/docs/introduction/getting_started/
#

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ prometheus_install_path }}"
    - "{{ prometheus_config_path }}"

- name: install prometheus
  include: install-prometheus.yml

- name: install prometheus-cache
  include: install-prometheus-cache.yml

- name: install alertmanager
  include: install-alertmanager.yml

- name: Copy prometheus service file
  template:
    src: 'prometheus.service'
    dest: '/etc/systemd/system/prometheus.service'

- name: Copy prometheus-cache service file
  template:
    src: 'prometheus-cache.service'
    dest: '/etc/systemd/system/prometheus-cache.service'

- name: Copy alertmanager service file
  template:
    src: 'alertmanager.service'
    dest: '/etc/systemd/system/alertmanager.service'

- name: Start the prometheus service
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Start the prometheus-cache service
  systemd:
    name: prometheus-cache
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Start the alertmanager service
  systemd:
    name: alertmanager
    state: restarted
    daemon_reload: yes
    enabled: yes