---
# file: tasks/main.yml
# Top-level installer for Prometheus.
#
# @see https://github.com/prometheus/prometheus
# @see http://prometheus.io/docs/introduction/getting_started/
#

- name: mkdir for general cases
  file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ prometheus_install_path }}"
    - "{{ prometheus_config_path }}"

- name: install prometheus
  include: install-prometheus.yml

- name: install pushgateway
  include: install-prometheus-pushgateway.yml

- name: Copy prometheus service file
  template:
    src: 'prometheus.service'
    dest: '/etc/systemd/system/prometheus.service'

- name: Copy pushgateway service file
  template:
    src: 'pushgateway.service'
    dest: '/etc/systemd/system/pushgateway.service'

- name: Start the prometheus service
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Start the pushgateway service
  systemd:
    name: pushgateway
    state: restarted
    daemon_reload: yes
    enabled: yes
