- name: Copy cron tab
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'pull_images', dest: '/etc/cron.hourly/pull_images'}
    - {src: 'remove_old_pkg', dest: '/etc/cron.weekly/remove_old_pkg'}