version: "3.7"

# Standard logging for each service
x-logging: &logging_anchor
  driver: "json-file"
  options:
    max-size: "10mb"
    max-file: "10"

# Standard volumes mounted
x-volumes: &volumes_anchor
  - ${ROOTCA_PATH}:/var/opt/magma/certs/rootCA.pem
  - ${CONTROL_PROXY_PATH}:/etc/magma/control_proxy.yml
  - ${CERTS_VOLUME}:/var/opt/magma/certs
  - ${CONFIGS_OVERRIDE_VOLUME}:/var/opt/magma/configs
  - ${CONFIGS_DEFAULT_VOLUME}:/etc/magma
  - ../../../orc8r/gateway/configs/templates:/etc/magma/templates
  - /etc/snowflake:/etc/snowflake

# Generic python anchor to avoid repetition for python services
x-pyservice: &pyservice
  image: ${DOCKER_REGISTRY}gateway_python:${IMAGE_VERSION}
  volumes: *volumes_anchor
  logging: *logging_anchor
  restart: always
  network_mode: host

services:
  control_proxy:
    <<: *pyservice
    container_name: control_proxy
    command: >
      sh -c "/usr/local/bin/generate_nghttpx_config.py &&
             /usr/bin/env nghttpx --conf /var/opt/magma/tmp/nghttpx.conf /var/opt/magma/certs/controller.key /var/opt/magma/certs/controller.crt"

  magmad:
    <<: *pyservice
    container_name: magmad
    build:
      context: ../../../ # TODO: Move feg/gateway/docker/python to magma/orc8r/gateway/docker
      dockerfile: feg/gateway/docker/python/Dockerfile
    volumes:
      - ${ROOTCA_PATH}:/var/opt/magma/certs/rootCA.pem
      - ${CONTROL_PROXY_PATH}:/etc/magma/control_proxy.yml
      - ${CERTS_VOLUME}:/var/opt/magma/certs
      - ${CONFIGS_OVERRIDE_VOLUME}:/var/opt/magma/configs
      - ${CONFIGS_DEFAULT_VOLUME}:/etc/magma
      - ../../../orc8r/gateway/configs/templates:/etc/magma/templates
      - /etc/snowflake:/etc/snowflake
      - /var/run/docker.sock:/var/run/docker.sock
    command: python3 -m magma.magmad.main

  metricsd:
    <<: *pyservice
    container_name: metricsd
    volumes: *volumes_anchor
    command: python3 -m magma.metricsd.main