---
swagger: '2.0'
info:
  title: Gateway Materialized View Definitions
  description: Only the definitions section matters here. paths, info, and swagger are only here to validate against spec
  version: 1.0.0

paths:
  /networks/{network_id}/gateways?view=full:
    get:
      summary: Get materialized views of gateways specified in input
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: query
        name: gateway_ids
        type: array
        required: false
        items:
          type: string
      responses:
        '200':
          description: Materialized views of gateways specified in query
          schema:
            type: array
            items:
              $ref: '#/definitions/gateway_state'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

definitions:
  gateway_state:
    type: object
    required:
      - gateway_id
      - offset
    properties:
      gateway_id:
        $ref: './swagger-common.yml#/definitions/gateway_id'
      config:
        type: object
        additionalProperties:
          type: object
      status:
        $ref: '#/definitions/gateway_status'
      record:
        $ref: '#/definitions/access_gateway_record'
      offset:
        type: integer
        format: uint64
        x-nullable: false
  system_status:
    type: object
    properties:
      time:
        type: integer
        format: uint64
        example: 1234567000
      cpu_user:
        type: integer
        format: uint64
        x-go-custom-tag: 'magma_alt_name:"CpuUser"'
      cpu_system:
        type: integer
        format: uint64
        x-go-custom-tag: 'magma_alt_name:"CpuSystem"'
      cpu_idle:
        type: integer
        format: uint64
        x-go-custom-tag: 'magma_alt_name:"CpuIdle"'
      mem_total:
        type: integer
        format: uint64
      mem_available:
        type: integer
        format: uint64
      mem_used:
        type: integer
        format: uint64
      mem_free:
        type: integer
        format: uint64
      uptime_secs:
        type: integer
        format: uint64
        example: 12345
  gateway_status:
    type: object
    properties:
      checkin_time:
        type: integer
        format: uint64
        example: 1234567890
      hardware_id:
        type: string
      version:
        type: string
      system_status:
        $ref: '#/definitions/system_status'
      cert_expiration_time:
        type: integer
        format: int64
        example: 1234567890
      meta:
        type: object
        additionalProperties:
          type: string
      vpn_ip:
        type: string
        example: 10.0.0.1
      kernel_version:
        type: string
        example: 4.9.0-6-amd64
      kernel_versions_installed:
        type: array
        x-omitempty: true
        items:
          type: string
        example: ["4.9.0-6-amd64", "4.9.0-7-amd64"]
  hw_gateway_id:
    type: object
    required:
    - id
    properties:
      id:
        type: string
        minLength: 1
        x-nullable: false
        x-go-custom-tag: 'magma_alt_name:"Id"'
        example: 22ffea10-7fc4-4427-975a-b9e4ce8f6f4d
  access_gateway_record:
    type: object
    required:
    - hw_id
    - key
    properties:
      hw_id:
        $ref: '#/definitions/hw_gateway_id'
        x-go-custom-tag: 'magma_alt_name:"HwId"'
      name:
        type: string
        minLength: 1
        example: South Park's CtPa Town Tower
      key:
        $ref: '#/definitions/challenge_key'
  challenge_key:
    type: object
    required:
    - key_type
    properties:
      key_type:
        type: string
        enum:
        - ECHO
        - SOFTWARE_ECDSA_SHA256
        example: SOFTWARE_ECDSA_SHA256
        x-nullable: false
      key:
        type: string
        format: byte
        x-nullable: true
        example: MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE+Lckvw/eeV8CemEOWpX30/5XhTHKx/mm6T9MpQWuIM8sOKforNm5UPbZrdOTPEBAtGwJB6Uk9crjCIveFe+sN0zw705L94Giza4ny/6ASBcctCm2JJxFccVsocJIraSC