version: "3.7"

services:
  validator:
    build:
      context: ..
      dockerfile: ./validator/Dockerfile
    volumes:
      - $PWD/validate.json:/validate.json:ro
      - $PWD/validate.yang:/validate.yang:ro
