---
swagger: '2.0'
info:
  title: Policiesdb Model Definitions and Paths
  description: Magma REST APIs
  version: 1.1.2

paths:
  /networks/{network_id}/policies/rules:
    get:
      summary: List policy rules
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: List of policy rules
          schema:
            type: array
            items:
              $ref: '#/definitions/rule_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Add a new policy rule
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: Policy rule
        description: Policy rule to add
        required: true
        schema:
          $ref: '#/definitions/policy_rule'
      responses:
        '201':
          description: Rule id
          schema:
            $ref: '#/definitions/rule_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
  /networks/{network_id}/policies/rules/{rule_id}:
    get:
      summary: Get policy rule
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/rule_id'
      responses:
        '200':
          description: Policy rule on success
          schema:
            $ref: '#/definitions/policy_rule'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify a policy rule
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/rule_id'
      - in: body
        name: Policy rule
        description: Policy rule
        required: true
        schema:
          $ref: '#/definitions/policy_rule'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete a policy rule
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/rule_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
  /networks/{network_id}/policies/base_names:
    get:
      summary: List Charging Rule Base Names
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: List of Charging Rule Base Names
          schema:
            $ref: '#/definitions/rule_names'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Create Charging Rule Base Name
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: Charging Rule Base Name
        description: Charging Rule Base Name to add
        required: true
        schema:
          $ref: '#/definitions/base_name_record'
      responses:
        '201':
          description: Charging Rule Base Name
          schema:
            $ref: '#/definitions/base_name'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
  /networks/{network_id}/policies/base_names/{base_name}:
    get:
      summary: Get Charging Rule Base Name
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/base_name'
      responses:
        '200':
          description: Charging Rule Base Name on success
          schema:
            $ref: '#/definitions/rule_names'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify a Charging Rule Base Name
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/base_name'
      - in: body
        name: Charging Rule Base Name
        description: Charging Rule Base Name
        required: true
        schema:
          $ref: '#/definitions/rule_names'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete a Charging Rule Base Name
      tags:
      - Policies
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/base_name'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

responses:
  # Common responses
  UnexpectedError:
    description: Unexpected Error
    schema:
      $ref: './swagger-common.yml#/definitions/error'

parameters:
  rule_id:
    in: path
    name: rule_id
    description: Rule Id
    required: true
    type: string
  base_name:
    in: path
    name: base_name
    description: Charging Rule Base Name
    required: true
    type: string

definitions:
  rule_id:
    # A unique human readable identifier for labeling a policy rule
    type: string
    minLength: 1
    x-nullable: false
    example: All ICMP
  flow_description:
    type: object
    properties:
      action:
        type: string
        enum:
        - PERMIT
        - DENY
        default: PERMIT
      match:
        $ref: '#/definitions/flow_match'
        x-nullable: false
  flow_qos:
    type: object
    properties:
      max_req_bw_ul:
        type: integer
        format: uint32
      max_req_bw_dl:
        type: integer
        format: uint32
  redirect_information:
    type: object
    properties:
      support:
        type: string
        enum:
        - DISABLED
        - ENABLED
      address_type:
        type: string
        enum:
        - IPv4
        - IPv6
        - URL
        - SIP_URI
      server_address:
        type: string
  policy_rule:
    # A traffic match template and a identifier that is
    # used to labelling usage records
    type: object
    properties:
      id:
        type: string
        x-nullable: false
        example: All ICMP
        x-go-custom-tag: 'magma_alt_name:"Id"'
      flow_list:
        type: array
        items:
          $ref: '#/definitions/flow_description'
          x-nullable: false
      priority:
        type: integer
        format: uint32
        default: 10
      rating_group:
        type: integer
        format: uint32
        x-nullable: true
      monitoring_key:
        type: string
        x-nullable: true
      tracking_type:
        type: string
        enum:
        - ONLY_OCS
        - ONLY_PCRF
        - OCS_AND_PCRF
        - NO_TRACKING
      qos:
        $ref: '#/definitions/flow_qos'
        x-nullable: true
      redirect:
        $ref: '#/definitions/redirect_information'
        x-nullable: true
  base_name:
    type: string
    minLength: 1
    x-nullable: false
  rule_names:
    type: array
    items:
      type: string
      x-nullable: false
  base_name_record:
    type: object
    properties:
      name:
        $ref: '#/definitions/base_name'
        x-nullable: false
      rule_names:
        $ref: '#/definitions/rule_names'
        x-nullable: false
  flow_match:
    # A template for matching traffic to meter
    type: object
    properties:
      ip_proto:
        type: string
        enum:
        - IPPROTO_IP
        - IPPROTO_TCP
        - IPPROTO_UDP
        - IPPROTO_ICMP
        x-nullable: true
        default: IPPROTO_IP
      ipv4_src:
        type: string
        format: ip-address
        example: "192.168.0.1/24"
        x-go-custom-tag: 'magma_alt_name:"Ipv4Src"'
      ipv4_dst:
        type: string
        format: ip-address
        example: "0.0.0.0/0"
        x-go-custom-tag: 'magma_alt_name:"Ipv4Dst"'
      tcp_src:
        type: integer
        format: uint32
        x-go-custom-tag: 'magma_alt_name:"TcpSrc"'
      tcp_dst:
        type: integer
        format: uint32
        x-go-custom-tag: 'magma_alt_name:"TcpDst"'
      udp_src:
        type: integer
        format: uint32
        x-go-custom-tag: 'magma_alt_name:"UdpSrc"'
      udp_dst:
        type: integer
        format: uint32
        x-go-custom-tag: 'magma_alt_name:"UdpDst"'
      direction:
        type: string
        enum:
        - UPLINK
        - DOWNLINK
        x-nullable: false