---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Copy magma service unit file
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'magma_metricsd.service', dest: '/etc/systemd/system/magma@metricsd.service'}

- name: Restart the magma services
  systemd: name=magma@{{ item }} state=restarted daemon_reload=yes enabled=yes
  with_items:
      - metricsd
