sudo: required
language: node_js

node_js:
  - '10'

sudo: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxi-dev ca-certificates build-essential
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn run test
  - yarn run eslint ./

notifications:
  webhooks: https://code.facebook.com/travis/webhook/
