---
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
log_level: INFO

# List of services for magmad to control
magma_services:
  - control_proxy
  - metricsd

# List of services that don't provide service303 interface
non_service303_services:
  - control_proxy

# List of all possible dynamic services (enabled from gateway.mconfig)
registered_dynamic_services:

# list of services that are required to have meta before checking in
# (meta = data gathered via MagmaService.register_get_status_callback())
# skip limit specified by config 'max_skipped_checkins'
skip_checkin_if_missing_meta_services: []

# Init system to use to control services
# Supported systems include: [systemd, runit, docker]
init_system: docker

# bootstrap_manager config
bootstrap_config:
  # location of the challenge key
  challenge_key: /var/opt/magma/certs/gw_challenge.key

# Flags indicating the magmad features to be enabled
enable_config_streamer: True
enable_upgrade_manager: False
enable_network_monitor: True
enable_systemd_tailer: False
enable_sync_rpc: True
enable_kernel_version_checking: True

systemd_tailer_poll_interval: 30 # seconds

mconfig_modules:
  - orc8r.protos.mconfig.mconfigs_pb2
  - lte.protos.mconfig.mconfigs_pb2
  - feg.protos.mconfig.mconfigs_pb2
