---
# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
log_level: INFO
collect_interval: 60 # How frequently to collect metrics samples in seconds
sync_interval: 60 # How frequently to sync to cloud in seconds
grpc_timeout: 30 # Timeout in seconds
queue_length: 1000 # Number of failed samples to enqueue for resend
# List of services for metricsd to poll
services:
    - magmad
